apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  selector:
    app: alpine-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort   # Exposes service on a port of the Minikube node