apiVersion: v1
kind: Pod
metadata:
  name: alpine-web
  labels:
    app: alpine-web
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          apk add --no-cache busybox-extras && \
          while true; do \
            echo -e "HTTP/1.1 200 OK\r\n\r\nHello from Alpine!" | nc -l -p 8080; \
          done
      ports:
        - containerPort: 8080
