apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://aks-cluste-aks-pls-rg-b80625-fv63qwxe.hcp.canadacentral.azmk8s.io:443
  name: aks-cluster
- cluster:
    certificate-authority: /home/jahangir/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 13 Sep 2025 11:30:37 PKT
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://myaksclust-rg-aks-canada-b80625-s6sih0h1.hcp.canadacentral.azmk8s.io:443
  name: myAKSCluster
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://mycompany-aks-dev-xmxrgw0i.hcp.canadacentral.azmk8s.io:443
  name: mycompany-aks-dev
contexts:
- context:
    cluster: aks-cluster
    user: clusterUser_aks-pls-rg_aks-cluster
  name: aks-cluster
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 13 Sep 2025 11:30:37 PKT
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
- context:
    cluster: myAKSCluster
    user: clusterUser_rg-aks-canada_myAKSCluster
  name: myAKSCluster
- context:
    cluster: mycompany-aks-dev
    user: clusterUser_aks-demo-rg_mycompany-aks-dev
  name: mycompany-aks-dev
current-context: minikube
kind: Config
users:
- name: clusterUser_aks-demo-rg_mycompany-aks-dev
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
    token: REDACTED
- name: clusterUser_aks-pls-rg_aks-cluster
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
    token: REDACTED
- name: clusterUser_rg-aks-canada_myAKSCluster
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
    token: REDACTED
- name: minikube
  user:
    client-certificate: /home/jahangir/.minikube/profiles/minikube/client.crt
    client-key: /home/jahangir/.minikube/profiles/minikube/client.key
