name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
env:
  REGISTRY: ghcr.io

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # GitHub automatically provides the username of the workflow actor
          username: ${{ github.actor }}
          # GitHub provides a built-in authentication token to push images securely
          # No need to manually create or store a PAT (Personal Access Token)
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧩 Extract and sanitize ref name
        id: vars
        run: |
          sha_short=$(git rev-parse --short HEAD)
          ref_name=${GITHUB_REF_NAME////-}  # Replace '/' with '-'
          echo "sha_short=$sha_short" >> $GITHUB_OUTPUT
          echo "ref_name=$ref_name" >> $GITHUB_OUTPUT
      
      - name: 🏗️ Build and Push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/next-layer-technology/coordinator:latest
            ${{ env.REGISTRY }}/next-layer-technology/coordinator:${{ steps.vars.outputs.ref_name }}
            ${{ env.REGISTRY }}/next-layer-technology/coordinator:${{ steps.vars.outputs.sha_short }}
